version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ciuster/hellodocker:1.0
    #environment:
    #  PAROLADORDINE: "il fosso saltalo te"
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: