version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ciuster/hellodocker:1.0
    environment:
      PAROLADORDINE: "questa volta lo saltiamo in gruppo"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: