version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: pippo

    volumes:
      - ./db_persistent_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    image: webdocker
    #build: .
    ports:
        - "4000:80"
    volumes:
      - ./web/:/var/www/html/
